---
abstract: 'calculate what quarter a given date is in'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-QuarterOfYear
requires:
  Carp: '0'
  Exporter: '0'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Date-QuarterOfYear
  repository: https://github.com/neilbowers/Date-QuarterOfYear.git
version: '0.01'
